project_id = "wylrkmtpjodunmnwncej"

# Sync and data management functions - v1.0.2
[functions.sync-noddi-data]
verify_jwt = false

[functions.compute-segments]
verify_jwt = false

[functions.compute-pyramid-tiers]
verify_jwt = false

[functions.clear-segments]
verify_jwt = false

[functions.test-noddi-connection]
verify_jwt = false

[functions.test-organizations]
verify_jwt = false

[functions.test-user-groups]
verify_jwt = false

[functions.reset-database]
verify_jwt = false

[functions.reset-order-lines]
verify_jwt = false

# Automatic deployment recovery - v1.0.1
[functions.force-full-sync]
verify_jwt = false

[functions.sync-diagnostics]
verify_jwt = false

[functions.compute-value-tiers]
verify_jwt = false