project_id = "wylrkmtpjodunmnwncej"

[functions.sync-noddi-data]
verify_jwt = false

[functions.compute-segments]
verify_jwt = false

[functions.test-noddi-connection]
verify_jwt = false

[functions.test-organizations]
verify_jwt = false

[functions.test-user-groups]
verify_jwt = false

[functions.reset-database]
verify_jwt = false